### The  Pandas Library
Series & Data frames

In [3]:
import pandas as pd
import numpy as np

In [5]:
#creating  Series using Series() constructor
ser1 = pd.Series([45,67,-4,89])
print(ser1)
print(ser1.index)
print(ser1.values)

0    45
1    67
2    -4
3    89
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[45 67 -4 89]

In [17]:
#you can also pass numpy array in the series
a1 = np.arange(6)
s1 = pd.Series((a1),index = [100,200,300,400,500,600])
print(s1)

100    0
200    1
300    2
400    3
500    4
600    5
dtype: int64

In [46]:
s1[600] = 4500
print(s1)
print(a1)

100       0
200       1
300       2
400       3
500       4
600    4500
dtype: int64
[   0    1    2    3    4 4500]

In [45]:
print(df1.columns)
print(df1.index)
print(df1.values)

Index(['Product', 'Price', 'Color'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
[['Pen' 30 'red']
 ['Pencil' 40 'blue']
 ['Erasor' 50 'white']
 ['Marker' 60 'black']]

In [34]:
#creating a dataframe using np.arange
pd = pd.DataFrame((np.arange(15).reshape(3,5)),index = ['row1','row2','row3'],columns = ['col1','col2','col3','col4','col5'])
print(pd)

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [36]:
pd.col2

row1     1
row2     6
row3    11
Name: col2, dtype: int64

In [37]:
pd[0:2]

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9

In [41]:
pd.head(2)                        #print first 2 rows

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9

In [40]:
pd.tail(1)                          #print last 1 rows

      col1  col2  col3  col4  col5
row3    10    11    12    13    14